owner: Adityacprtm
repo: uptime
user-agent: Adityacprtm

sites:
  - name: Website
    url: https://adityacprtm.dev
    icon: https://adityacprtm.dev/img/icons/favicon-32x32.png
    maxResponseTime: 5000
  - name: API
    url: https://api.adityacprtm.dev/status
    icon: https://api.adityacprtm.dev/favicon.ico
    maxResponseTime: 5000

status-website:
  cname: uptime.adityacprtm.dev
  theme: dark
  logoUrl: https://res.cloudinary.com/adityacprtm/image/upload/v1634915700/adityacprtm_x_upptime_114ad9ba02.png
  name: Uptime | Adityacprtm
  favicon: https://adityacprtm.dev/img/icons/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
